# Intermediate Queries
# 1. Calculate the number of orders per month in 2018.

use ecommerse;

SELECT monthname(orders.order_purchase_timestamp) as Month, count( orders.order_id ) NO_Orders
 from orders GROUP BY Month ORDER BY Month ;
 
#  2. Find the average number of products per order, grouped by customer city.

SELECT customer_city as city,  avg( customers.customer_id )  from customers GROUP BY city ;

#  3. Calculate the percentage of total revenue contributed by each product category.





SELECT 
    products.product_category AS category,
    
    round(SUM(order_items.price + order_items.freight_value) / (SELECT 
            ROUND(SUM(price + freight_value), 2)
        FROM
            order_items) * 100.0 ,2 ) as Percent
FROM
    products
        JOIN
    order_items ON products.product_id = order_items.product_id
GROUP BY category;



# 5. Calculate the total revenue generated by each seller, and rank them by revenue.



select seller.seller_id as Seller , round(sum(order_items.price),2 ) as Revenue
from seller join order_items 
on seller.seller_id = order_items.seller_id 
group by Seller
order by Revenue Desc
;




